1. 'Applied steps' show us what we did with our project while working with PowerBI;
2. There's a 'Remove Rows' button on the 'Home' ribbon. Maximize that then you can find a button called 'Remove Duplicates';
3. We can apply various filters with this button.
4. Double-tap the column name, and change it;
5. Power Query Editor closes, and applies every changes you made to Power BI Desktop;
6. Click the filter icon next to the 'Quantity' column name and uncheck number 2;
7. Select the column. Then click 'Add Column' ribbon, and find 'Date' button. After that press 'Year', 'Month' and 'Day' buttons;
8. Select the column and press 'Replace Values' button on 'Transform' ribbon.
	Value to Find: Mouse
	Replace With: Computer Mouse;
9. Click the filter button near the column name. Then choose 'Sort Descending';
10. I'd filter them out pressing filter button, and uncheck NULL;
11. 
```let
    Source = YourPreviousStep,  // Replace with your actual source step
    AddedTotalSpent = Table.AddColumn(Source, "TotalSpent", each [Quantity] * [Price], type number)
in
    AddedTotalSpent```
12. Right click CustID, then 'Group By'. After that choose 'Operation' 'Sum', 'Column' 'TotalSales'.
13. On the left part of the column name there's a DataType column. Click it and choose 'Date';
14. Go to Home → Click Transform Data.

In Power Query Editor, go to the Add Column tab.

Click on Conditional Column.

In the dialog that appears:

New column name: OrderLabel (or any name you like)

Column name: Price

Operator: is greater than

Value: 100

Output: High Value

15. OK.

